### ISSUE TITLE
got below error while initiating the class

### ISSUE THREAD

**Issue by tiru1930** [hughperkins/pytorch#38]
Traceback (most recent call last):
  File "pythonwrap.py", line 5, in <module>
    tansclass=Torchclass()
  File "/home/tiru/qgencode/qgen/lib/python3.5/site-packages/PyTorch-4.1.1_SNAPSHOT-py3.5-linux-x86_64.egg/PyTorchHelpers.py", line 20, in __init__
    PyTorchAug.LuaClass.__init__(self, splitName, *args)
  File "/home/tiru/qgencode/qgen/lib/python3.5/site-packages/PyTorch-4.1.1_SNAPSHOT-py3.5-linux-x86_64.egg/PyTorchAug.py", line 255, in __init__
    raise Exception(errorMessage)
Exception: attempt to call a nil value

**Comment by hughperkins** [comment]
I *think* it looks like it cant find `Torchclass` in the LUA_PATH/LUA_CPATH etc. I think you might want to double-check how these env vars look, maybe try running the unit tests, check they run ok, ie https://github.com/hughperkins/pytorch/blob/master/run_tests.sh

**Comment by tiru1930** [comment]
Thank you .. I am able to do this after running test cases

**Comment by hughperkins** [comment]
Ok. You mean, all is working ok now?

**Comment by tiru1930** [comment]
Yes I was able to do it .. I was able to call my torch class from Python

**Comment by hughperkins** [comment]
Ok, great! :)
